### ISSUE TITLE
HUD Breaks

### ISSUE THREAD

**Issue by 7ekhed** [JustInvoke/Randomation-Vehicle-Physics#28]
Its me again. Sry, but whenever I edited the Menu just to rearrange the buttons, the HUD stopped working and various parts of the car no longer worked, like the automatic shift. Plz help, because this has happened alot. P.S. i fixed my previous issue

**Comment by RandomationGames** [comment]
The VehicleMenu script links certain properties to the menu buttons, one of them being automatic shifting. If you rearrange or disable certain buttons you could accidentally disable this. You could comment out the line that sets the auto shifting based on the button so that the value retains what it's set to on the prefab.

The VehicleMenu script is one of the weaker parts of this repository because it was designed for the sake of the demo scene, not so much for people to use it in their actual games. I should have designed it to be more flexible/modular; maybe sometime in the future I'll refactor it.

**Comment by JustInvoke** [comment]
It's not likely, sorry.

**Comment by JustInvoke** [comment]
I've added a new VehicleHud script with prefabs for the HUD. Now the HUD functionality is separate from the menu. Inside the Terrain Example scene you can see where the HUD prefab was added by itself without the menu.
