### ISSUE TITLE
Hi, there your control is very impressive.

### ISSUE THREAD

**Issue by MuhammadWaqasOfficial** [JustInvoke/Randomation-Vehicle-Physics#46]
Hi, there your control is very impressive.
Just want to share a view about project hierarchy management. Isn't it better to place all folders in single folder with name of RandomationVehiclePhysics folder. Just for us(users) as we have own things as well in project. It might get messy.
Also i am making mobile game. So will looking forward to add Left/Right Buttons & Steering wheel functionality. 
Regards
Muhammad Waqas

**Comment by JustInvoke** [comment]
Unfortunately this repository has to act like a complete project because it requires the project settings to be set a certain way and they are not contained in the Assets folder. Users would have to manually adjust the project settings rather than just clone the repository and have it work automatically.

Part of this also results from how the project was organized when it was sold on the asset store.

**Comment by MuhammadWaqasOfficial** [comment]
Understand. Thanks brother
